name: e_commerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

#.................Package...............#
dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.2.4
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific


#.................Package...............#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/fonts/
     - assets/icons/
     - assets/images/on_boarding_images/
     - assets/logos/

# Flutter native splash configuration
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/splash_Logo_black.png
  image_dark: assets/logos/splash_Logo_white.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/splash_Logo_black.png
    image_dark: assets/logos/splash_Logo_white.png

  web: false